language: node_js
cache:
  directories:
    # https://twitter.com/maybekatz/status/905213355748720640
    - ~/.npm
node_js:
  - '8'

branches:
  only:
    - master

stages:
  - commitlint
  - test
  - name: release
    if: branch = master AND type IN (push)

jobs:
  include:
    - stage: commitlint
      script: commitlint-travis
    - stage: test
      script: npm test
    - stage: release
      script: npm run release

